# Generated by Django 5.2.7 on 2025-11-13 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistemascomputo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('pais_origen', models.CharField(max_length=54, verbose_name='País de origen')),
                ('ram', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='RAM (TB)')),
                ('rom', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ROM (TB)')),
                ('flops', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='TeraFLops')),
                ('so', models.CharField(blank=True, choices=[('AlmaLinux', 'AlmaLinux'), ('CentOS', 'CentOS'), ('Debian', 'Debian'), ('FreeBSD', 'FreeBSD'), ('Linux', 'Linux'), ('Oracle Linux', 'Oracle Linux'), ('Red Hat Enterprise Linux', 'Red Hat Enterprise Linux'), ('Rocky Linux', 'Rocky Linux'), ('SUSE Linux Enterprise Server', 'SUSE Linux Enterprise Server'), ('Ubuntu Server', 'Ubuntu Server'), ('Unix', 'Unix'), ('Windows Server', 'Windows Server'), ('Otro', 'Otro')], max_length=30, verbose_name='Sistema Operativo')),
            ],
        ),
    ]
